README.md

Closes #4.
Hopefully this may attract new developers to the project?

Link Discord server to README

---

nova_vm/src/heap.rs
nova_vm/src/heap/array_buffer.rs
nova_vm/src/heap/heap_bits.rs
nova_vm/src/heap/indexes.rs
nova_vm/src/heap/object.rs
nova_vm/src/types/language/value.rs

Adding to the heap implementation, this time with a small and incorrect implementation for a constructor as well.

feat(heap): ArrayBuffer

---

nova_vm/src/execution/agent.rs
nova_vm/src/execution/environments.rs
nova_vm/src/execution/environments/declarative_environment.rs
nova_vm/src/execution/environments/function_environment.rs
nova_vm/src/execution/environments/global_environment.rs
nova_vm/src/execution/environments/object_environment.rs
nova_vm/src/execution/environments/private_environment.rs
nova_vm/src/execution/execution_context.rs
nova_vm/src/execution/realm.rs
nova_vm/src/execution/realm/intrinsics.rs
nova_vm/src/heap.rs
nova_vm/src/language/bytecode/executable.rs

Somewhat of a confused mess with the lifetimes flying around, of which I'm really not sure if we even care about... But it's here! The very first function to call before you start running JavaScript code on the engine!

feat(realm): Implement initialize_host_defined_realm function

---

nova_vm/src/ecmascript/abstract_operations/operations_on_objects.rs
nova_vm/src/ecmascript/abstract_operations/testing_and_comparison.rs
nova_vm/src/ecmascript/abstract_operations/type_conversion.rs
nova_vm/src/ecmascript/builtins.rs
nova_vm/src/ecmascript/builtins/array.rs
nova_vm/src/ecmascript/builtins/array_buffer.rs
nova_vm/src/ecmascript/builtins/builtin_function.rs
nova_vm/src/ecmascript/builtins/ordinary.rs
nova_vm/src/ecmascript/execution.rs
nova_vm/src/ecmascript/execution/realm.rs
nova_vm/src/ecmascript/execution/realm/intrinsics.rs
nova_vm/src/ecmascript/types.rs
nova_vm/src/ecmascript/types/language.rs
nova_vm/src/ecmascript/types/language/function.rs
nova_vm/src/ecmascript/types/language/object.rs
nova_vm/src/ecmascript/types/language/object/internal_methods.rs
nova_vm/src/ecmascript/types/language/object/internal_slots.rs
nova_vm/src/ecmascript/types/language/string.rs
nova_vm/src/ecmascript/types/language/value.rs
nova_vm/src/heap.rs

Also cleanup, change InternalMethods trait to take `self` parameters (better matches the spec as well), run clippy, ...

feat(ecmascript): Implement OrdinaryObjectInternalSlots trait

---

nova_vm/src/ecmascript/types/language/bigint.rs

fix(bigint): use correct operator for bitwise not

---

nova_vm/src/ecmascript/abstract_operations/operations_on_objects.rs
nova_vm/src/ecmascript/builtins/ordinary.rs
nova_vm/src/ecmascript/execution/realm.rs
nova_vm/src/ecmascript/scripts_and_modules/script.rs
nova_vm/src/ecmascript/syntax_directed_operations/statements_and_declarations.rs
nova_vm/src/ecmascript/types/language/object.rs
nova_vm/src/ecmascript/types/language/object/property_storage.rs
nova_vm/src/engine/bytecode/executable.rs
nova_vm/src/engine/bytecode/vm.rs
nova_vm/src/heap.rs
nova_vm/src/heap/element_array.rs

Adds basic support for CreateObject bytecode.

feat(vm): CreateObject

---

nova_vm/src/engine/bytecode/instructions.rs
nova_vm/src/heap/element_array.rs

fix(ub): Fix undefined behaviour

---

nova_vm/src/ecmascript/scripts_and_modules/script.rs
nova_vm/src/engine/bytecode/executable.rs
nova_vm/src/engine/bytecode/instructions.rs
nova_vm/src/engine/bytecode/vm.rs

The engine can now handle if-else branching.
Next step will be basic for-loops.

feat(vm): Implement if-else statement

---

nova_vm/src/ecmascript/abstract_operations/testing_and_comparison.rs
nova_vm/src/ecmascript/scripts_and_modules/script.rs
nova_vm/src/ecmascript/types/language/number.rs
nova_vm/src/ecmascript/types/spec/reference.rs
nova_vm/src/engine/bytecode/executable.rs
nova_vm/src/engine/bytecode/instructions.rs
nova_vm/src/engine/bytecode/vm.rs

feat(vm): for loop

---

nova_vm/Cargo.toml

An artifact from a time long gone...

chore(deps): remove `gc` crate

---

nova_vm/src/ecmascript/abstract_operations/testing_and_comparison.rs
nova_vm/src/ecmascript/builtins/ordinary.rs
nova_vm/src/ecmascript/scripts_and_modules/script.rs
nova_vm/src/ecmascript/types/language/string.rs
nova_vm/src/engine/bytecode/executable.rs
nova_vm/src/engine/bytecode/instructions.rs
nova_vm/src/engine/bytecode/vm.rs

Kind of messy- I was just going through a few of the TODOs.

feat: support getter logic, `SameValueNonNumber(String, String)`, `+`, `!`, and `~`

---

nova_vm/src/ecmascript/builtins.rs
nova_vm/src/ecmascript/builtins/array.rs
nova_vm/src/ecmascript/builtins/array/abstract_operations.rs
nova_vm/src/ecmascript/builtins/array/data.rs
nova_vm/src/ecmascript/scripts_and_modules/script.rs
nova_vm/src/ecmascript/types/language/object.rs
nova_vm/src/ecmascript/types/language/object/property_storage.rs
nova_vm/src/engine/bytecode/executable.rs
nova_vm/src/engine/bytecode/instructions.rs
nova_vm/src/engine/bytecode/vm.rs
nova_vm/src/heap/element_array.rs
nova_vm/src/heap/heap_bits.rs

Kind of a dirty implementation of `ArrayCreate`. The `array_set_length` and related abstract operations and functions are particularly dirty as they need to work around the `length` special case.

feat(vm): ArrayCreate

---

nova_vm/src/ecmascript.rs
nova_vm/src/ecmascript/abstract_operations/operations_on_objects.rs
nova_vm/src/ecmascript/builtins/builtin_function.rs
nova_vm/src/ecmascript/builtins/number.rs
nova_vm/src/ecmascript/builtins/ordinary.rs
nova_vm/src/ecmascript/execution/realm.rs
nova_vm/src/ecmascript/execution/realm/intrinsics.rs
nova_vm/src/ecmascript/fundamental_objects.rs
nova_vm/src/ecmascript/fundamental_objects/object_objects.rs
nova_vm/src/ecmascript/fundamental_objects/object_objects/object_constructor.rs
nova_vm/src/ecmascript/scripts_and_modules/script.rs

Building on top of #103 this PR now starts showing how nice and easy it becomes to create constructors.

feat(ecmascript): Intrinsics creation

---

Cargo.toml
nova_vm/Cargo.toml
nova_vm/build.rs
nova_vm/src/builtin_strings
nova_vm/src/ecmascript/builtins/ecmascript_function.rs
nova_vm/src/ecmascript/execution/agent.rs
nova_vm/src/ecmascript/execution/environments.rs
nova_vm/src/ecmascript/execution/environments/declarative_environment.rs
nova_vm/src/ecmascript/execution/environments/function_environment.rs
nova_vm/src/ecmascript/execution/environments/global_environment.rs
nova_vm/src/ecmascript/execution/environments/object_environment.rs
nova_vm/src/ecmascript/execution/environments/private_environment.rs
nova_vm/src/ecmascript/scripts_and_modules/script.rs
nova_vm/src/ecmascript/syntax_directed_operations/function_definitions.rs
nova_vm/src/ecmascript/syntax_directed_operations/scope_analysis.rs
nova_vm/src/ecmascript/types/spec/reference.rs
nova_vm/src/engine/bytecode/executable.rs
nova_vm/src/engine/bytecode/vm.rs

chore(vm): Update oxc version

---

nova_vm/src/ecmascript/scripts_and_modules/script.rs
nova_vm/src/engine/bytecode/executable.rs
nova_vm/src/engine/bytecode/instructions.rs
nova_vm/src/engine/bytecode/vm.rs

feat(vm): Implement try-catch

---

Cargo.toml
nova_vm/src/ecmascript/scripts_and_modules/script.rs
nova_vm/src/ecmascript/syntax_directed_operations/scope_analysis.rs
nova_vm/src/engine/bytecode/executable.rs
nova_vm/tests/sources/objectPrototype.test.js

I have a pretty bad feeling about this. The changes were mind-numbingly boring to type through, but not very trivial. Hence there's a good chance that errors have crept in. Tests still pass.

chore: Update oxc

---

nova_cli/src/main.rs
nova_vm/src/ecmascript/builtins/fundamental_objects/symbol_objects/symbol_prototype.rs
nova_vm/src/ecmascript/builtins/keyed_collections/map_objects/map_constructor.rs
nova_vm/src/ecmascript/builtins/keyed_collections/map_objects/map_prototype.rs
nova_vm/src/ecmascript/builtins/numbers_and_dates/number_objects/number_constructor.rs
nova_vm/src/ecmascript/builtins/numbers_and_dates/number_objects/number_prototype.rs
nova_vm/src/ecmascript/builtins/primitive_objects.rs

Building on top of #211, this does a few minor things here and there.

feat(ecmascript): Miscellaneous work

---

nova_vm/src/ecmascript/builtins/array.rs
nova_vm/src/ecmascript/builtins/data_view.rs
nova_vm/src/ecmascript/builtins/module.rs
nova_vm/src/ecmascript/builtins/proxy.rs
nova_vm/src/ecmascript/types/language/function.rs

fix(ecmascript): Array [[Get]] method does not access prototype properties

---

nova_vm/src/ecmascript/builtins/array/abstract_operations.rs
tests/expectations.json

Assigning a shorter length wasn't properly deleting the old data.

fix(ecmascript): Array length assignment

---

nova_vm/src/ecmascript/types/language/string/data.rs

According to the spec, the maximum length of a string is 2^53 - 1 UTF-16 code units. Since Nova's strings are UTF-8, and we only compute their UTF-16 length and indices lazily, we cannot fulfill this restriction as is. Instead, when a heap string is created, we check that its UTF-8 length could correspond to a valid UTF-16 length. Then, when and if we compute the UTF-16 mapping, we panic if that would result in an invalid UTF-16 length.

fix(ecmascript): Enforce the spec's limits on string length

---

tests/test262_runner.rs

https://github.com/trynova/nova/pull/356#issuecomment-2254798380

fix(tests): Behaviour of `--update` flag

---

nova_cli/src/helper.rs

Helper to enable reading text files from nova_cli. This is kind of building up to parsing failed tests by name and grouping them into "what's highest up on the list?" kind of thing. The `tests/parse_expectation.js` script accidentally made it into the main already.

feat(cli): readTextFile

---

nova_vm/src/ecmascript/builtins/ecmascript_function.rs
nova_vm/src/ecmascript/syntax_directed_operations/function_definitions.rs
nova_vm/src/ecmascript/types/language/function/data.rs
nova_vm/src/engine/bytecode/executable.rs

Entry step towards supporting class instance field initializers.

feat(vm): Store compiled bytecode in ECMAScriptFunctionHeapData

---

nova_vm/src/ecmascript/types/language/object.rs
nova_vm/src/ecmascript/types/language/value.rs
nova_vm/src/engine/rootable.rs

fix(engine): Rootable features usage

---

nova_cli/src/main.rs
nova_vm/build.rs
nova_vm/src/ecmascript/abstract_operations/operations_on_objects.rs
nova_vm/src/ecmascript/abstract_operations/testing_and_comparison.rs
nova_vm/src/ecmascript/builtins/ecmascript_function.rs
nova_vm/src/ecmascript/builtins/fundamental_objects/object_objects/object_constructor.rs
nova_vm/src/ecmascript/builtins/numbers_and_dates/date_objects/date_prototype.rs
nova_vm/src/ecmascript/builtins/text_processing/regexp_objects/regexp_prototype.rs
nova_vm/src/ecmascript/execution/agent.rs
nova_vm/src/ecmascript/execution/environments.rs
nova_vm/src/ecmascript/execution/environments/global_environment.rs
nova_vm/src/ecmascript/execution/environments/object_environment.rs
nova_vm/src/ecmascript/scripts_and_modules/script.rs
nova_vm/src/engine/bytecode/executable.rs
nova_vm/src/engine/bytecode/iterator.rs
nova_vm/src/engine/bytecode/vm.rs
nova_vm/tests/garbage_collection_tests.rs

Just added these methods. Didn't really use them yet, much.

feat(ecmascript): Try methods for environments

---

nova_vm/src/ecmascript/types/language/value.rs

feat: implement PartialEq for ValueRootRepr

---

nova_vm/src/ecmascript/builtins/control_abstraction_objects/async_function_objects/async_function_constructor.rs
nova_vm/src/ecmascript/builtins/control_abstraction_objects/async_generator_function_objects/async_generator_function_constructor.rs
nova_vm/src/ecmascript/builtins/control_abstraction_objects/generator_function_objects/generator_function_constructor.rs
nova_vm/src/ecmascript/builtins/control_abstraction_objects/promise_objects/promise_constructor.rs
nova_vm/src/ecmascript/builtins/fundamental_objects/boolean_objects/boolean_constructor.rs
nova_vm/src/ecmascript/builtins/fundamental_objects/error_objects/aggregate_error_constructors.rs
nova_vm/src/ecmascript/builtins/fundamental_objects/error_objects/error_constructor.rs
nova_vm/src/ecmascript/builtins/fundamental_objects/error_objects/native_error_constructors.rs
nova_vm/src/ecmascript/builtins/fundamental_objects/function_objects/function_constructor.rs
nova_vm/src/ecmascript/builtins/fundamental_objects/object_objects/object_constructor.rs
nova_vm/src/ecmascript/builtins/fundamental_objects/symbol_objects/symbol_constructor.rs
nova_vm/src/ecmascript/builtins/indexed_collections/array_objects/array_constructor.rs
nova_vm/src/ecmascript/builtins/indexed_collections/typed_array_objects/typed_array_intrinsic_object.rs
nova_vm/src/ecmascript/builtins/keyed_collections/map_objects/map_constructor.rs
nova_vm/src/ecmascript/builtins/keyed_collections/set_objects/set_constructor.rs
nova_vm/src/ecmascript/builtins/keyed_collections/weak_map_objects/weak_map_constructor.rs
nova_vm/src/ecmascript/builtins/keyed_collections/weak_set_objects/weak_set_constructor.rs
nova_vm/src/ecmascript/builtins/managing_memory/finalization_registry_objects/finalization_registry_constructor.rs
nova_vm/src/ecmascript/builtins/managing_memory/weak_ref_objects/weak_ref_constructor.rs
nova_vm/src/ecmascript/builtins/numbers_and_dates/bigint_objects/bigint_constructor.rs
nova_vm/src/ecmascript/builtins/numbers_and_dates/date_objects/date_constructor.rs
nova_vm/src/ecmascript/builtins/numbers_and_dates/number_objects/number_constructor.rs
nova_vm/src/ecmascript/builtins/reflection/proxy_constructor.rs
nova_vm/src/ecmascript/builtins/structured_data/array_buffer_objects/array_buffer_constructor.rs
nova_vm/src/ecmascript/builtins/structured_data/data_view_objects/data_view_constructor.rs
nova_vm/src/ecmascript/builtins/structured_data/shared_array_buffer_objects/shared_array_buffer_constructor.rs
nova_vm/src/ecmascript/builtins/text_processing/regexp_objects/regexp_constructor.rs
nova_vm/src/ecmascript/builtins/text_processing/string_objects/string_constructor.rs

Just some tidying around the house. Busywork to avoid doing the hard things.

chore(ecmascript): Rename behaviour fns to constructors to better match JavaScript semantics

---

tests/metrics.json

chore(test262): Update metrics

---

nova_vm/src/ecmascript/abstract_operations/operations_on_iterator_objects.rs
nova_vm/src/ecmascript/abstract_operations/operations_on_objects.rs
nova_vm/src/ecmascript/builders/builtin_function_builder.rs
nova_vm/src/ecmascript/builders/ordinary_object_builder.rs
nova_vm/src/ecmascript/builtins.rs
nova_vm/src/ecmascript/builtins/array.rs
nova_vm/src/ecmascript/builtins/array/abstract_operations.rs
nova_vm/src/ecmascript/builtins/array/data.rs
nova_vm/src/ecmascript/builtins/bound_function.rs
nova_vm/src/ecmascript/builtins/control_abstraction_objects/promise_objects/promise_constructor.rs
nova_vm/src/ecmascript/builtins/ecmascript_function.rs
nova_vm/src/ecmascript/builtins/error.rs
nova_vm/src/ecmascript/builtins/fundamental_objects/function_objects/function_prototype.rs
nova_vm/src/ecmascript/builtins/fundamental_objects/object_objects/object_constructor.rs
nova_vm/src/ecmascript/builtins/ordinary.rs
nova_vm/src/ecmascript/builtins/regexp.rs
nova_vm/src/ecmascript/builtins/structured_data/json_object.rs
nova_vm/src/ecmascript/types/language/function/into_function.rs
nova_vm/src/ecmascript/types/language/object.rs
nova_vm/src/ecmascript/types/language/object/data.rs
nova_vm/src/ecmascript/types/language/object/internal_slots.rs
nova_vm/src/ecmascript/types/language/object/property_storage.rs
nova_vm/src/engine/small_integer.rs
nova_vm/src/heap.rs
nova_vm/src/heap/element_array.rs
nova_vm/src/heap/heap_bits.rs
nova_vm/src/heap/heap_gc.rs
nova_vm/src/heap/indexes.rs
small_string/lib.rs

More heap vectors! Mwahahaha! Mooooore!
But now it's clearer where keys and values are, and how they're stored.

feat(heap): Separate key and value storage

---

nova_vm/src/ecmascript/execution/weak_key.rs

fix(ecmascript): WeakKey::Symbol discriminant

---

nova_vm/src/ecmascript/builtins/indexed_collections/array_objects/array_prototype.rs
tests/expectations.json
tests/metrics.json

Just going through the expectations and doing some easy fixes 😅

fix(ecmascript): Behaviour of `Array.prototype.includes` larger than length `fromIndex` argument

---

nova_vm/src/ecmascript/builtins/indexed_collections/array_objects/array_prototype.rs
tests/expectations.json
tests/metrics.json

A bit of a follow up to the previous one

fix(ecmascript): Behaviour of `Array.prototype.indexOf` larger than length `fromIndex` argument

---

nova_vm/Cargo.toml
nova_vm/src/builtin_strings
nova_vm/src/ecmascript/builtins/numbers_and_dates/math_object.rs

Implements @CanadaHonk's [`Math.clamp`](https://github.com/tc39/proposal-math-clamp/) proposal!

feat(ecmascript): Implement `Math.clamp` proposal

---

nova_vm/src/engine/bytecode/instructions.rs

For me these small changes pushed the performance of richards.js from ~95 to > ~100.

perf(engine): Optimize hot-paths of instruction methods
