trynova/nova

- nova_vm/src/heap.rs
- nova_vm/src/heap/array.rs
- nova_vm/src/heap/array_buffer.rs
- nova_vm/src/heap/bigint.rs
- nova_vm/src/heap/boolean.rs
- nova_vm/src/heap/date.rs
- nova_vm/src/heap/element_array.rs
- nova_vm/src/heap/error.rs
- nova_vm/src/heap/function.rs
- nova_vm/src/heap/heap_bits.rs
- nova_vm/src/heap/heap_gc.rs
- nova_vm/src/heap/math.rs
- nova_vm/src/heap/number.rs
- nova_vm/src/heap/object.rs
- nova_vm/src/heap/regexp.rs
- nova_vm/src/heap/symbol.rs
- nova_vm/src/types/language/object/property_key.rs
Take the `types/language/object/property_key.rs` PropertyKey into use.
> chore: Remove duplicate PropertyKey enum

- nova_vm/src/ecmascript/builtins.rs
- nova_vm/src/ecmascript/builtins/array.rs
- nova_vm/src/ecmascript/builtins/array_buffer.rs
- nova_vm/src/ecmascript/builtins/ordinary.rs
- nova_vm/src/ecmascript/execution/realm/intrinsics.rs
- nova_vm/src/ecmascript/types/language/object.rs
- nova_vm/src/ecmascript/types/language/object/property_key.rs
Implements `ArrayBuffer` properly as a sub-type of `Object` (and `Value`). This PR should serve as a good guideline on how `Object` sub-types are implemented at their most basic, though `ArrayBuffer` is probably the only one that is quite as simple as this.
> feat(ecmascript): Implement ArrayBuffer Object sub-type

- nova_vm/src/ecmascript/types/language/number.rs
This refactors the old code that used to convert to a value before matching on itself to use the enum variants.
> refactor(number): remove value conversion indirection

- nova_vm/src/ecmascript/types/language/number.rs
Previously had inverted results. Also optimised the floating-point implementations.
> fix(ecmascript) fix Number::is_odd_integer

- nova_vm/src/ecmascript/types/language/number.rs
https://github.com/trynova/nova/blob/main/nova_vm/src/ecmascript/types/language/number.rs#L165
`!n.is_sign_negative() && !n.is_sign_positive()` is always false.
> fix(ecmascript) Fix Number::is_nonzero

- nova_vm/src/ecmascript/types/language/number.rs
this fixes a `todo` comment in `Number::is` referring to the spec for `Object.is`.
`Object.is` is implemented via `SameValue(x, y)`, which in turn has a separate branch for numbers: `Number::SameValue`.
This is the rest of the implementation.
I also identified that `Number::is` was being used in places where the spec wanted pretty much simple equality, as opposed to `SameValue`? Although they would both fit.
We should try to get some helpers for comparisons and operations soon, the code is overtly verbose. I'll write some ideas on the Discord server.
> Finish Number::SameValue

- nova_vm/src/engine/small_integer.rs
Since `SmallInteger` represents numbers in two's complement, the minimum value for that type is -2^55, rather than -2^55 + 1, even though its maximum value is 2^55 - 1. This is because there are as many negative numbers representable in the type as non-negative numbers, but the non-negative numbers include zero. This patch updates `SmallInteger::MIN_BIGINT` to reflect this.
This patch also updates `SmallInteger::{MIN,MAX}_NUMBER` to remove the division by 2, to make them truly reflect Javascript's `Number.{MIN,MAX}_SAFE_INTEGER`. It also changes the ranges in `SmallInteger::from_i64_unchecked` and in the `TryFrom<i64>` impl to use `{MIN,MAX}_BIGINT`, rather than `{MIN,MAX}_NUMBER`.
> fix(vm): Fix the ranges for `SmallInteger`

- nova_vm/src/ecmascript/types/language/number.rs
- nova_vm/src/ecmascript/types/language/value.rs
- nova_vm/src/engine/small_integer.rs
This patch also makes `SmallInteger::from_i64_unchecked` a private method, to prevent misuse.
-----------
This PR depends on #58 and should not land before it.
> feat(vm): Add conversions from integer types to `SmallInteger`

- nova_vm/src/ecmascript/types/language/number.rs
- nova_vm/src/ecmascript/types/language/object/property_key.rs
- nova_vm/src/ecmascript/types/language/string.rs
- nova_vm/src/ecmascript/types/language/value.rs
- nova_vm/src/engine/small_integer.rs
- nova_vm/src/heap.rs
- nova_vm/src/heap/heap_gc.rs
- nova_vm/src/heap/math.rs
- nova_vm/src/heap/number.rs
- nova_vm/src/heap/symbol.rs
These functions do not check the invariants that the parameters must keep to, so they're naturally unsafe.
I had to also refactor the way the `Number` enum is instantiated.
> feat(heap): Make number and string allocation functions unsafe

- nova_vm/src/ecmascript/abstract_operations/testing_and_comparison.rs
- nova_vm/src/ecmascript/abstract_operations/type_conversion.rs
- nova_vm/src/ecmascript/types/language/bigint.rs
This pr implements the is_loosely_equal and is_strictly_equal operators. ~~is_loosely_equal still contains some `todo!`s for the stuff I was unsure about, mostly having to do with bigint related operations.~~
> feat(ecmascript): is_loosely_equal and is_strictly_equal

- nova_vm/src/ecmascript/abstract_operations.rs
- nova_vm/src/ecmascript/abstract_operations/operations_on_iterator_objects.rs
Adds some of the [operations on iterator objects](https://tc39.es/ecma262/#sec-operations-on-iterator-objects).
> feat(ecmascript): operations on iterator objects

- nova_vm/src/ecmascript/abstract_operations/testing_and_comparison.rs
- nova_vm/src/ecmascript/builtins/number.rs
Now, we only need to finish the `Number` constructor, `Number.parseFloat`, and `Number.parseInt`.
> feat(builtins): more `Number` constructor methods

- nova_vm/src/ecmascript/builtins/ordinary.rs
I am unsure if this was intentional (or if I wrote this code), but I noticed this while doing a fly-by of the ordinary methods.
> fix(builtins): make ordinary methods use `SameValue`

- nova_vm/src/ecmascript/execution/realm.rs
We now pass around realms as identifier which allows us to avoid locking thanks to AapoAlas's idea.
> feat: better Agent <=> Realm relationship

- nova_vm/src/heap/README.md
No idea what I was smoking when I wrote this. `gc` crate is a tracing GC.
> Fix invalid statement about Boa engine's gc being reference counting

- nova_vm/src/ecmascript/builtins/array_buffer/abstract_operations.rs
- nova_vm/src/ecmascript/types/spec/data_block.rs
I originally had used u32 to match what V8 did at the time but they've upped their max ArrayBuffer size and there's little reason why we wouldn't as well: This does grow the ArrayBuffer heap data to 150% of its previous size but that's life.
> feat(ecmascript): Increase ArrayBuffer max size to usize

- nova_vm/src/ecmascript/builtins.rs
- nova_vm/src/ecmascript/builtins/arguments.rs
- nova_vm/src/ecmascript/builtins/builtin_function.rs
- nova_vm/src/ecmascript/builtins/ecmascript_function.rs
- nova_vm/src/ecmascript/execution.rs
- nova_vm/src/ecmascript/execution/agent.rs
- nova_vm/src/ecmascript/execution/environments.rs
- nova_vm/src/ecmascript/execution/environments/declarative_environment.rs
- nova_vm/src/ecmascript/execution/realm/intrinsics.rs
- nova_vm/src/ecmascript/scripts_and_modules/script.rs
- nova_vm/src/ecmascript/syntax_directed_operations/function_definitions.rs
- nova_vm/src/ecmascript/syntax_directed_operations/scope_analysis.rs
- nova_vm/src/engine/bytecode/executable.rs
This PR implements calling of functions for simple cases. At least the following parts are left for the future:
1. Parameter default values
2. Spread parameters
The calling of functions is done in the worst way possible: A new "Vm" is created every time that a function body evaluation starts. There is absolutely no elegance in this :)
> feat(vm): Implement function calling

- nova_vm/src/ecmascript/execution.rs
- nova_vm/src/ecmascript/execution/realm.rs
- nova_vm/src/ecmascript/scripts_and_modules/script.rs
- nova_vm/src/engine/bytecode/executable.rs
- nova_vm/src/engine/bytecode/instructions.rs
- nova_vm/src/engine/bytecode/vm.rs
Implements basic `StaticMemberExpression` (`object.identifier`) and `ComputedMemberExpression` (`object["expression"]`) member expressions. Still left to do is a few tests, and `integer`/`symbol` computed member expressions.
> feat(vm): implement `ComputedMemberExpression` and `StaticMemberExpression`

- nova_vm/src/ecmascript/scripts_and_modules/script.rs
- nova_vm/src/ecmascript/syntax_directed_operations/scope_analysis.rs
- nova_vm/src/engine/bytecode/executable.rs
- nova_vm/src/engine/bytecode/instructions.rs
- nova_vm/src/engine/bytecode/vm.rs
This PR adds support for lexical declarations, ie. `let` and `const`. At the same time the bytecode received the possibility of entering and exiting lexical scopes (lexical environments) as well as creating and initializing bindings in them. A smarter engine would probably precalculate these but we're not like the others! Ha! In your face!
> feat(vm): Lexical declarations

- Cargo.toml
- nova_cli/Cargo.toml
- nova_vm/Cargo.toml
This stops us from having to make manually sure all crates (currently 2) depend on the same version of each crate.
> chore(deps): use Cargo workspace

- nova_vm/src/ecmascript/builtins/arguments.rs
- nova_vm/src/ecmascript/builtins/array.rs
- nova_vm/src/ecmascript/builtins/array/abstract_operations.rs
- nova_vm/src/ecmascript/builtins/array_buffer/abstract_operations.rs
- nova_vm/src/ecmascript/builtins/builtin_function.rs
- nova_vm/src/ecmascript/builtins/ecmascript_function.rs
- nova_vm/src/ecmascript/builtins/ordinary.rs
- nova_vm/src/ecmascript/execution/realm.rs
- nova_vm/src/ecmascript/execution/realm/intrinsics.rs
- nova_vm/src/ecmascript/types/language/function.rs
- nova_vm/src/ecmascript/types/language/object.rs
- nova_vm/src/heap.rs
- nova_vm/src/heap/array.rs
- nova_vm/src/heap/array_buffer.rs
- nova_vm/src/heap/bigint.rs
- nova_vm/src/heap/boolean.rs
- nova_vm/src/heap/date.rs
- nova_vm/src/heap/error.rs
- nova_vm/src/heap/function.rs
- nova_vm/src/heap/heap_bits.rs
- nova_vm/src/heap/heap_constants.rs
- nova_vm/src/heap/heap_gc.rs
- nova_vm/src/heap/math.rs
- nova_vm/src/heap/number.rs
- nova_vm/src/heap/object.rs
- nova_vm/src/heap/regexp.rs
- nova_vm/src/heap/string.rs
- nova_vm/src/heap/symbol.rs
Building on top of #102 this PR refactors the `Intrinsics` struct to be a lot smaller (only 8 bytes now) and fills it in to fully define the all the intrinsic objects, constructors and functions mentioned in the spec.
> Refactor Intrinsics

- nova_vm/src/ecmascript/builtins/module.rs
- nova_vm/src/ecmascript/builtins/module/data.rs
- nova_vm/src/ecmascript/builtins/ordinary.rs
- nova_vm/src/ecmascript/execution.rs
- nova_vm/src/ecmascript/execution/environments.rs
- nova_vm/src/ecmascript/execution/environments/module_environment.rs
- nova_vm/src/heap.rs
I'll probably be using this as a "show-off" on how to implement internal methods for most exotic objects. Module strikes a relative nice balance: It doesn't have special properties by-name in itself but on the other hand it does through the exported properties. It's also has quite a bit of special internal method definitions but those are fairly simple.
Hopefully this will serve as a good template for others on how to go about doing this for other object types.
> feat(ecmascript): Module object internal methods

- nova_vm/src/ecmascript/scripts_and_modules/script.rs
- nova_vm/src/ecmascript/types/language/object/property_storage.rs
- nova_vm/src/engine/bytecode/executable.rs
- nova_vm/src/heap/element_array.rs
This patch implements object property assignment (`a.b = c`).
Additionally, in order to make an assertion in `ordinary_set_with_own_descriptor` not fail, it also implements `PropertyStorage::has` on objects, as well as fixes a stack overflow in `ElementArray::has` caused by the fact that the element arrays were being stored on the stack as part of the computation.
> feat(ecmascript): Add object property assignment

- nova_vm/src/ecmascript/execution/agent.rs
- nova_vm/src/engine/bytecode/vm.rs
The current implementation of `Vm::execute` uses the `?` operator to propagate JS exceptions to the caller. This currently only works because we don't implement try-catch, since `?` does not allow catching an `Err` result value within the current function.
This patch adds an `execute_instruction` method, which handles the execution of a single instruction, which lets the `execute` method handle its non-successful result value.
However, this would not work with `return` statements, since they are implemented by returning a value from `execute`. To fix this, we add a `ContinuationKind` enum, which we use as the successful return type of `execute_instruction`, to be able to tell apart what the spec calls normal vs return completions.
> chore(vm): Refactor `Vm::execute` to allow for try-catch

- nova_vm/build.rs
- nova_vm/src/builtin_strings
- nova_vm/src/ecmascript/abstract_operations/operations_on_iterator_objects.rs
- nova_vm/src/ecmascript/abstract_operations/operations_on_objects.rs
- nova_vm/src/ecmascript/abstract_operations/type_conversion.rs
- nova_vm/src/ecmascript/builtins/indexed_collections/array_objects/array_constructor.rs
This PR implements the array constructor builtin functions according to spec.
Closes #143
> feat(ecmascript): implement array constructor builtins

- nova_vm/src/ecmascript/builtins/ecmascript_function.rs
- nova_vm/src/ecmascript/scripts_and_modules/script.rs
- nova_vm/src/ecmascript/types/spec/reference.rs
- nova_vm/src/engine/bytecode/vm.rs
This patch adds bindings for function arguments for functions that have simple parameter lists (no bindings, initializers or spread arguments).
This wasn't implemented before because the spec text uses iterator machinery to handle complex parameters, resulting in all arguments evaluating to `undefined`. However, for simple parameter lists, the implementation is simple enough, so this patch implements it.
> feat(ecmascript): Function argument bindings for simple parameter lists

- nova_vm/src/engine/bytecode/executable.rs
- nova_vm/src/engine/bytecode/vm.rs
Previously the only supported comparison operators were `<`, `===` and `!==`. This patch adds support for the rest of comparison operators (namely `<=`, `>`, `>=`, `==` and `!=`), as well as the `in` operator, and also unifies bytecode generation for all binary operators.
> feat(ecmascript): Implement comparison and `in` operators

- CONTRIBUTING.md
Explicitly define a code of conduct for pull requests. This is first and foremost here to explain why I prefix all my PR comments with eg. `**praise:**` or `**issue:**` or such, and what I mean by them :)
Also mentioned is Conventional Commits which I'm not quite so strict about but figured I'd put it there anyway.
> doc(contributing): Pull Request Code of Conduct

- nova_vm/src/ecmascript/builtins/ordinary.rs
- nova_vm/src/ecmascript/scripts_and_modules/script.rs
- nova_vm/src/ecmascript/types/language/object/property_storage.rs
- nova_vm/src/heap/element_array.rs
Although currently JS user code can't define getters and setters, there is one usage in internal Nova code in the creation of the `arguments` object for non-lexical-this functions. This change makes it possible to call such functions without panicking.
> feat(ecmascript): Support getters and setters in `PropertyStorage`

- nova_vm/src/ecmascript/builders/builtin_function_builder.rs
- nova_vm/src/ecmascript/scripts_and_modules/script.rs
When built-in functions are created, the `initial_name` and `length` fields of `BuiltinFunctionHeapData` are populated. This means that, if there is no backing object when the function is created, the `name` and `length` properties will have the value given by those fields. This is the case even if a backing object needs to be created later on, since those fields will be added to the backing object.
However, if properties are added to the built-in function as it is being constructed, then there will be a backing object without the `name` and `length` properties, so they will appear to not be set. This is always the case for built-in constructor functions, since they will always have a `prototype` property.
The long-term fix for this would be to avoid duplicating heap data fields in the …
> fix(ecmascript): Make sure built-in functions have `name` and `length`

- nova_vm/src/ecmascript/builtins/arguments.rs
- nova_vm/src/ecmascript/builtins/ecmascript_function.rs
- nova_vm/src/ecmascript/builtins/fundamental_objects/boolean_objects/boolean_constructor.rs
- nova_vm/src/ecmascript/builtins/fundamental_objects/error_objects/error_constructor.rs
- nova_vm/src/ecmascript/builtins/fundamental_objects/error_objects/native_error_constructors.rs
- nova_vm/src/ecmascript/builtins/fundamental_objects/object_objects/object_constructor.rs
- nova_vm/src/ecmascript/builtins/indexed_collections/array_objects/array_constructor.rs
- nova_vm/src/ecmascript/builtins/numbers_and_dates/date_objects/date_constructor.rs
- nova_vm/src/ecmascript/builtins/ordinary.rs
- nova_vm/src/engine/bytecode/vm.rs
Per the spec, OrdinaryCreateFromConstructor should get the `prototype` property of the passed constructor, and if that is an object, it should create a new object whose prototype is that property; otherwise, the prototype would be set to the passed intrinsic default prototype.
In the current implementation of this method, the `prototype` of the passed constructor is obtained, but then it is ignored. The given intrinsic default prototype is used to determine in which heap to store the object, which gives it the right default prototype, but it does not check whether the constructor's `prototype` property matches that default prototype.
It seems like this gets the right result for all of the times where Nova currently does object construction. However, allowing creating an object with a …
> feat(ecmascript): Allow object creation with a different prototype

- nova_vm/src/ecmascript/abstract_operations/testing_and_comparison.rs
- nova_vm/src/ecmascript/builtins/ecmascript_function.rs
- nova_vm/src/ecmascript/scripts_and_modules/script.rs
As part of making this work, this patch merges the internal slots `[[ConstructorKind]]` and `[[IsClassConstructor]]`, as well as the presence or absence of the `[[Construct]]` internal method (which hadn't been implemented in Nova yet) into a single `ConstructorStatus` enum.
> feat(ecmascript): Allow constructing ECMAScript functions

- nova_vm/src/ecmascript/execution.rs
- nova_vm/src/ecmascript/execution/environments.rs
- nova_vm/src/ecmascript/execution/environments/function_environment.rs
- nova_vm/src/ecmascript/scripts_and_modules/script.rs
- nova_vm/src/engine/bytecode/executable.rs
- nova_vm/src/engine/bytecode/vm.rs
This patch also fixes a bug in which functions created with the `InstantiateOrdinaryFunctionExpression` bytecode instruction were created with a lexical this mode, when it should be either strict or global. The lexical this mode is only used for arrow functions, and it causes the `this` resolution to be wrong in other functions.
Do not merge before #196.
> feat(ecmascript): Implement the `this` keyword

- nova_cli/src/main.rs
- nova_vm/src/ecmascript/execution/agent.rs
- nova_vm/src/engine/bytecode/executable.rs
- nova_vm/src/engine/bytecode/vm.rs
To reenable printing that information, this patch also adds a `--verbose` flag to `nova_cli`.
> chore(nova_cli): Don't print debug information by default

- nova_cli/src/main.rs
This flag was introduced in #199, but it mistakenly did nothing. This patch fixes that.
> fix(nova_cli): Fix the `--verbose` flag

- nova_cli/src/main.rs
- nova_vm/src/ecmascript/execution.rs
- nova_vm/src/ecmascript/types/language/value.rs
In order to implement this, this patch also publicly exposes `Realm` (since using that type is needed to call `initialize_host_defined_realm`), and it also adds a public `Value::to_string` method.
> feat(nova_cli): Add a `print` global function

- nova_cli/src/main.rs
This fixes oxc-project/oxc#3539.
> fix(cli): Make sure parse errors don't have color escapes on non-TTYs

- nova_vm/src/ecmascript/scripts_and_modules/script.rs
- nova_vm/src/ecmascript/types/language/object/property_key.rs
- nova_vm/src/engine/bytecode/executable.rs
- nova_vm/src/engine/bytecode/instructions.rs
- nova_vm/src/engine/bytecode/vm.rs
Some of the ugliest code I've done in a little while.
Basically: Add minimal support for array destructuring. It only works as long as `Array.prototype[Symbol.iterator]` is untouched and even then only basic destructuring works. It's mostly a miracle that even that works to begin with.
> feat(vm): Limited array destructuring support

- toolchain.toml
This pr adds a new file that specifies the rust version we use to develop nova
> chore(repo): Add minimal version of toolchain used

- README.md
This replaces a link to the timestamp where the Nova talk begins in the Web Engines Hackfest livestream with the link to the now-published standalone video for that talk.
> chore(readme): Link to the standalone Web Engines Hackfest video

- nova_vm/src/ecmascript/builtins/fundamental_objects/function_objects/function_prototype.rs
- nova_vm/src/ecmascript/types/language/function.rs
- nova_vm/src/engine/bytecode/executable.rs
The reference was being lost to parameter resolution.
> fix(vm): Properly pass this value to EvaluateCall

- nova_vm/src/ecmascript/types/language/string.rs
- nova_vm/src/heap.rs
- small_string/lib.rs
Currently small strings use the zero byte as filler between the end of the string and the end of the buffer. This makes it impossible to represent strings ending in `\0` as a small string, even if they fit the length requirements.
However, since small strings are always UTF-8, it is possible to use a byte like 0xFF as the filler byte, since valid UTF-8 (or WTF-8) strings will never contain that byte. This makes it possible to represent the null character at the end of a small string while distinguishing it from the end of the string.
> fix(small_string): Support null-terminated small strings

- nova_cli/Cargo.toml
Before #229, running `cargo run` on the root directory of the Nova checkout used to run the `nova_cli` binary, because that was the only binary in the workspace. However, that PR added the `test262` binary in the `tests` crate, which made the command for running the CLI be `cargo run --bin nova_cli`.
This patch fixes that by setting the `default-run` manifest key of the `nova_cli` crate to the `nova_cli` binary. Since that is the only `default-run` manifest key in the entire workspace, that will set the default behavior of `cargo run` across the workspace, while still making it possible to run the `test262` binary with the `--bin` flag.
> fix(repo): Make `cargo run` on the root directory run `nova_cli`

- tests/test262_runner.rs
This patch adds the `eval-test` subcommand to the test262 runner, which runs an individual test262 test in the same way the regular test262 runner would, except that it prints its output.
To be able to do this, this patch creates a `BaseTest262Runner` struct, which is used to run a single test and get its result, splitting it from the `Test262Runner` struct which walks through the test directories and compares the test results with a map of expectations.
> feat(tests): Add `eval-test` subcommand to the test262 runner

- nova_vm/src/ecmascript/builtins/indexed_collections/array_objects/array_prototype.rs
- nova_vm/src/ecmascript/builtins/numbers_and_dates/number_objects/number_constructor.rs
- nova_vm/src/ecmascript/types/language/number.rs
The `Number` ECMAScript type had a `From<i64>` implementation, although not all `i64` values can be converted to a `Number`. This implementation, in fact, casts the value into the safe integer range, which is not what is typically expected of the `From<T>` trait.
This patch instead turns this implementation into a `TryFrom<i64>` impl, which returns an `Err` when the value cannot be safely cast.
Additionally, since `Number` did not yet provide utility methods for converting to/from `usize`, which would be common for arrays and strings, this patch adds `TryFrom<usize>` and the `into_usize()` method. Notably, `number.into_usize()` is not equivalent to `number.into_i64() as usize` because negative numbers clamp to 0, rather than clamping to `i64::MIN` and subsequently being bytecast. …
> refactor(ecmascript): Improve conversions between Number and Rust numeric types

- nova_vm/src/ecmascript/execution/agent.rs
- nova_vm/src/ecmascript/execution/default_host_hooks.rs
The host hooks defined in the JS spec include multiple disparate things, from letting the host control on-demand code evaluation, to integration with HTML's concept of an incumbent realm, to enqueuing jobs for the host to later run.
Nova's current model only allows an all-or-nothing approach: either you implement `HostHooks` by yourself, in which case you don't have any of the spec-provided default implementations, or you use `DefaultHostHooks`, which does not let you customize them.
This does not work for host hooks such as `HostEnqueuePromiseJob` and other scheduling hooks, since the spec does not give default implementations. This makes sense, since it is up to the host, not to the JS engine, to determine job scheduling.
This patch moves the implementation of `HostHooks` methods from …
> refactor(ecmascript): Add default implementations to `HostHooks`

- nova_vm/src/ecmascript/builtins/control_abstraction_objects/promise_objects/promise_abstract_operations/promise_capability_records.rs
- nova_vm/src/ecmascript/builtins/promise/data.rs
- nova_vm/src/heap.rs
- nova_vm/src/heap/heap_bits.rs
- nova_vm/src/heap/heap_gc.rs
In the spec, Promise Capability Records contain a promise-like object as well as its resolve and reject functions. This is needed if you allow promise subclassing, which makes it so the resolve and reject functions might not be the ones the spec defines. However, for Nova's implementation of promises, we're only allowing built-in Promises (as well as thenables).
If we see a promise capability as giving you both a promise and a way to resolve it, we can instead implement that as a wrapper over `Promise` that gives you built-in `resolve` and `reject` methods. The promise resolving functions could then build *on top of* `PromiseCapability`, rather than vice versa. This would also mean that there wouldn't be a heap vector for promise capabilities themselves.
There's one remaining issue: there …
> refactor(ecmascript): Refactor `PromiseCapability` and `PromiseState`

- nova_cli/src/helper.rs
PR #210 added this workaround for oxc-project/oxc#3539, and it can now be removed.
> fix(cli): Remove workaround for non-TTY color escapes for parse errors

- tests/test262_runner.rs
> fix: Remove unnecessary dot when settings the binary extension for Windows in the test262 runner

- tests/test262_runner.rs
This caused some issues on Windows as [`PathBuf::canonicalize`](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.canonicalize) adds a `\\\\` in Windows Paths, causing `starts_with` to fail if the other path isn't canonicalized as well.
Solution? Just canonicalize the base tests path.
> fix: Canonicalize the base path of tests in test262_runner

- tests/test262_runner.rs
When running the test262 runner with the `--update-expectations` flag in Windows, the paths for any newly failing (or newly not-passing) tests will be added to `expectations.json` using backwards slashes as path separators. However, although Windows accepts both backwards and forwards slashes as path separators, Unix systems only accept forward slashes, and so those paths will not work on Unix OS's.
This patch fixes this by replacing backward with forward slashes in Windows in paths before adding them into the unexpected results map. It also fixes other minor issues with paths in Windows.
> fix(tests): Windows-related fixes to the test262 runner

- tests/metrics.json
- tests/test262_runner.rs
Introduces a new `--update-metrics` flag which outputs the metrics of the test run. It also introduces a shorthand flag `--update` (`-u`) which sets both `--update-metrics` and `--update-expectations` true.
> feat(tests): Introduce `--update-metrics` flag

- nova_vm/src/ecmascript/builtins/fundamental_objects/function_objects/function_prototype.rs
-> https://tc39.es/ecma262/#sec-function.prototype.apply
It seems like this was giving errors in the V8 benchmark suite.
> feat(vm): Support `ArrayLike` argument in `Function.prototype.apply`

- nova_vm/src/ecmascript/abstract_operations/operations_on_iterator_objects.rs
- nova_vm/src/ecmascript/execution/execution_context.rs
- nova_vm/src/ecmascript/syntax_directed_operations/function_definitions.rs
- nova_vm/src/ecmascript/types/language/object/property_key.rs
- nova_vm/src/ecmascript/types/spec/reference.rs
- nova_vm/src/engine/bytecode/executable.rs
- nova_vm/src/engine/bytecode/iterator.rs
- nova_vm/src/engine/bytecode/vm.rs
In order to allow `await` and `yield` to work, the execution state of a function at the time of evaluating an `await` or `yield` expression must be stored as part of one of the heap vectors, so it can later be resumed.
This means that `Vm`, `Executable` and `ExecutionContext` must implement `HeapMarkAndSweep`. This patch adds those implementations to those types, as well as many other internal types that did not already support GC tracing.
All such types must also implement `Send` and `Sync`, since the GC is meant to become multi-threaded in the future. This was not the case for `Executable`, since it includes static references into the oxc allocator, which is single-threaded. However, it would be fine to unsafely send those references across threads as long as they're only dereferenced …
> refactor: Allow storing VM and execution state in GC'd types

- nova_vm/src/ecmascript/builtins/control_abstraction_objects/promise_objects/promise_abstract_operations/promise_jobs.rs
- nova_vm/src/ecmascript/builtins/control_abstraction_objects/promise_objects/promise_abstract_operations/promise_reaction_records.rs
- nova_vm/src/ecmascript/builtins/control_abstraction_objects/promise_objects/promise_prototype.rs
In the spec, there are only two types of promise reaction handlers: callback handlers and empty handlers. The internal behavior of `await` and of other spec-internal machinery that depends on promise reactions simply creates JS functions backed by a spec-internal abstract closure and uses them as callback handlers.
These JS functions, however, should not be observable from JS code, and in fact they should only ever be handled by the engine code that deals with promise reactions. Therefore, our implementation of `await` will instead use a new variant of the `PromiseReactionHandler` enum.
To support this, however, there should be a way to invoke PerformPromiseThen with the `on_fulfilled` and `on_rejected` arguments being `PromiseReactionHandler`. To this end, `perform_promise_then` is made …
> refactor: Refactor promise reactions in preparation for `await`

- Cargo.toml
- nova_cli/Cargo.toml
- nova_cli/src/main.rs
```
cargo r repl
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.09s
Running `target/debug/nova_cli repl`
┌  Nova Repl (type exit or ctrl+c to exit)
│
└  Operation cancelled.
Error: Kind(Interrupted)
```
> fix(repl): restore terminal cursor on Ctrl-C signal

- nova_vm/src/ecmascript/abstract_operations/testing_and_comparison.rs
- nova_vm/src/ecmascript/builtins/array.rs
- nova_vm/src/ecmascript/builtins/array/data.rs
- nova_vm/src/ecmascript/builtins/keyed_collections/map_objects/map_constructor.rs
- nova_vm/src/ecmascript/builtins/keyed_collections/map_objects/map_prototype.rs
- nova_vm/src/ecmascript/builtins/keyed_collections/set_objects/set_constructor.rs
- nova_vm/src/ecmascript/builtins/keyed_collections/set_objects/set_prototype.rs
- nova_vm/src/ecmascript/builtins/map/data.rs
- nova_vm/src/ecmascript/builtins/set/data.rs
- nova_vm/src/ecmascript/execution/agent.rs
- nova_vm/src/ecmascript/types/language.rs
- nova_vm/src/ecmascript/types/language/bigint.rs
- nova_vm/src/ecmascript/types/language/number.rs
- nova_vm/src/ecmascript/types/language/primitive.rs
- nova_vm/src/ecmascript/types/language/string.rs
- nova_vm/src/ecmascript/types/language/value.rs
- nova_vm/src/heap.rs
- nova_vm/src/heap/element_array.rs
Yesterday I made Map and Set be actual hashmaps. There were two issues with this:
1. It contained a lot of unsafe blocks to skirt around borrow rules.
2. It did not fully handle mixed primitive and object hashmaps during garbage collection.
This PR fixes both issues. The first issue is fixed by introducing some intermediate types that can be used to index into primitive value heap data without holding the entire Agent hostage. This makes it possible to hold eg. a mutable borrow on a MapHeapData while still accessing data for heap strings, numbers, and bigints for hashing purposes.
The second point is fixed by adding a single (atomic) boolean into the MapHeapData and SetHeapData; if the boolean is true, then the internal hashtable is re-examined for and all primitive keys that had to be …
> chore(ecmascript): Remove unsafe usage in Map and Set constructors and methods, implement rehashing of primitives if needed

- nova_vm/src/engine/bytecode/executable.rs
- nova_vm/src/engine/bytecode/instructions.rs
- nova_vm/src/engine/bytecode/iterator.rs
- nova_vm/src/engine/bytecode/vm.rs
Array and object binding patterns can be either simple or complex, where simple patterns are compiled in a way that jumps into a separate execution context where only binding-related bytecode instructions are supported.
Currently, if an array or object binding pattern contains another binding pattern, that automatically makes the outer pattern complex. However, that doesn't need to be the case, as long as none of the nested patterns, no matter how deeply nested, have initializers or computed property keys.
As it turns out, the spec has a syntax-directed operation called `ContainsExpression` that checks exactly this, and which affects the behavior of `FunctionDeclarationInstantiation`. Our implementation currently does not use that, since we don't yet support bindings or initializers in …
> refactor(vm): Allow nested binding patterns to be simple

- nova_vm/src/engine/bytecode/executable.rs
- nova_vm/src/engine/bytecode/executable/class_definition_evaluation.rs
- nova_vm/src/engine/bytecode/executable/for_in_of_statement.rs
- nova_vm/src/engine/bytecode/executable/function_declaration_instantiation.rs
- nova_vm/src/engine/bytecode/vm.rs
- nova_vm/src/heap/heap_bits.rs
Built ontop of #419, this PR moves the under-construction Executable into `CompileContext` and makes it spit out an `Executable` at the end. This enables `Executable` to only contain boxed slices, reducing its size by one pointer per member. Additionally, the identifiers and constants vectors are combined to a single common boxed slice since both deal with what are effectively `Value`s.
An `Executable` now perfectly fits a cacheline (maybe I should align it to a cacheline as well...?), and it only has the APIs for compiling various ECMAScript sources and getting instructions. Perfect!
> feat(vm): Reduce Executable bytecode memory footprint

- CONTRIBUTING.md
Adds a small section with steps to run the test262 runner.
(It wasn't immediately clear to me that test262 was submoduled in, or that the nova_cli needed to be built first)
> docs(contributing): Add test runner example

- nova_vm/src/ecmascript/builtins/proxy.rs
- tests/metrics.json
I implemented the call method (also part of apply), but the number of crashes in test262 has increased. For example:
https://github.com/tc39/test262/blob/ff9763729d242b54a9f11bbc614670db3888c8d2/test/built-ins/Proxy/apply/call-result.js
When `p.call(Function.prototype.call)` is invoked, and p.apply is called, it results in the error:
Uncaught exception: TypeError: Not a callable value
I believe this is related to the following section of code:
https://github.com/trynova/nova/blob/55e48f94ed54b309f724ecbae28c2bd3f4b243ee/nova_vm/src/ecmascript/abstract_operations/testing_and_comparison.rs#L67-L89
Here, the issue is that it returns None. As the comment suggests, I suspect that if we change `Option<Function>` to `Option<Callable>`, the `try_into()` method would return true and resolve the …
> feat(ecmascript): proxy call method

- nova_vm/src/ecmascript/builtins/proxy.rs
- tests/metrics.json
It seems like test262 won’t pass without implementing Callable, so I’ll work on that first! https://github.com/trynova/nova/pull/510#issuecomment-2571660014
ref: https://github.com/trynova/nova/issues/160
doc: https://tc39.es/ecma262/#sec-proxy-object-internal-methods-and-internal-slots-construct-argumentslist-newtarget
> feat(ecmascript): Proxy constract

- nova_vm/src/ecmascript/builtins/text_processing/string_objects/string_prototype.rs
Ran test262 and found some issues in the annex-b tests. Related #548
> fix(ecmascript): `anchor` function length

- nova_vm/src/ecmascript/types/language/string.rs
- nova_vm/src/ecmascript/types/language/string/data.rs
- nova_vm/src/ecmascript/types/language/value.rs
- nova_vm/src/engine/bytecode/executable.rs
- nova_vm/src/engine/bytecode/vm.rs
- nova_vm/src/heap.rs
String hashing is currently always iterating the string twice: Once for `as_str` and once for `hash`.
String creation was also hashing twice: Once to lookup an existing string and once to store a new string.
String concatenation could also be optimised.
I also mildly refactored instruction fetching to make it a bit nicer, also a bit more performant if my quick check is correct.
> perf: String hashing, creation and concatenating

- nova_vm/src/ecmascript/builders/builtin_function_builder.rs
- nova_vm/src/ecmascript/builders/ordinary_object_builder.rs
- nova_vm/src/ecmascript/builders/property_builder.rs
- nova_vm/src/ecmascript/builtins/array.rs
- nova_vm/src/ecmascript/builtins/builtin_constructor.rs
- nova_vm/src/ecmascript/builtins/date.rs
- nova_vm/src/ecmascript/builtins/ecmascript_function.rs
- nova_vm/src/ecmascript/builtins/finalization_registry.rs
- nova_vm/src/ecmascript/builtins/indexed_collections/array_objects/array_prototype.rs
- nova_vm/src/ecmascript/builtins/map.rs
- nova_vm/src/ecmascript/builtins/module.rs
- nova_vm/src/ecmascript/builtins/numbers_and_dates/math_object.rs
- nova_vm/src/ecmascript/builtins/primitive_objects.rs
- nova_vm/src/ecmascript/builtins/proxy.rs
- nova_vm/src/ecmascript/builtins/typed_array.rs
- nova_vm/src/ecmascript/types/language/object/property_key.rs
- nova_vm/src/ecmascript/types/language/primitive.rs
- nova_vm/src/ecmascript/types/language/string.rs
- nova_vm/src/heap/element_array.rs
- nova_vm/src/heap/indexes.rs
- rust-toolchain.toml
- tests/expectations.json
- tests/metrics.json
CI is running Rust 1.85, but the rust-toolchain file in Nova was set to 1.81.
As a result, the following error occurs in CI.
```
error: failed to parse manifest at `/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/munge_macro-0.4.2/Cargo.toml`
Caused by:
feature `edition2024` is required
The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.81.0 (2dbb1af80 2024-08-20)).
Consider trying a newer version of Cargo (this may require the nightly release).
See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.
Error: Process completed with exit code 101.
```
In this PR, I unified the Cargo version used in Nova to 1.85 and ran …
> chore: update rust toolchain version by cargo 1.85

- .github/workflows/ci.yml
- Cargo.toml
- nova_lint/.cargo/config.toml
- nova_lint/Cargo.toml
- nova_lint/README.md
- nova_lint/rust-toolchain.toml
- nova_lint/src/agent_comes_first.rs
- nova_lint/src/gc_scope_comes_last.rs
- nova_lint/src/gc_scope_is_only_passed_by_value.rs
- nova_lint/src/lib.rs
- nova_lint/src/utils.rs
- nova_lint/ui/agent_comes_first.rs
- nova_lint/ui/agent_comes_first.stderr
- nova_lint/ui/gc_scope_comes_last.rs
- nova_lint/ui/gc_scope_comes_last.stderr
- nova_lint/ui/gc_scope_is_only_passed_by_value.rs
- nova_lint/ui/gc_scope_is_only_passed_by_value.stderr
- nova_vm/src/ecmascript/builtins/array_buffer/abstract_operations.rs
- nova_vm/src/ecmascript/builtins/indexed_collections/typed_array_objects/typed_array_intrinsic_object.rs
- nova_vm/src/ecmascript/builtins/numbers_and_dates/math_object.rs
- nova_vm/src/ecmascript/types/spec/property_descriptor.rs
- nova_vm/src/engine/context.rs
This is an initial take on #573 using dylint. I implemented three simple `agent_comes_first`, `gc_scope_comes_last` and `gc_scope_is_only_passed_by_value` rules just as a proof-of-concept and it's was actually rather fun and simple to implement!
It seems dylint requires rust nightly to build and test, which is why it's excluded from the main workspace and instead lives as it's entirely own crate with it's own `rust-toolchain`. I tried to get it to work alongside nova without nightly but nightly seems to be required to expose the internals of rust and allow us to use them to build our own clippy rules.
> feat(linter): Create `nova_lint` and implement three basic rules

- nova_vm/src/ecmascript/abstract_operations/operations_on_iterator_objects.rs
- nova_vm/src/ecmascript/abstract_operations/operations_on_objects.rs
- nova_vm/src/ecmascript/builtins/fundamental_objects/error_objects/aggregate_error_constructors.rs
- nova_vm/src/ecmascript/builtins/fundamental_objects/object_objects/object_constructor.rs
- nova_vm/src/ecmascript/builtins/indexed_collections/array_objects/array_constructor.rs
- nova_vm/src/ecmascript/builtins/indexed_collections/typed_array_objects/typed_array_constructors.rs
- nova_vm/src/ecmascript/builtins/keyed_collections/map_objects/map_constructor.rs
- nova_vm/src/ecmascript/builtins/keyed_collections/set_objects/set_constructor.rs
- nova_vm/src/ecmascript/builtins/numbers_and_dates/math_object.rs
- nova_vm/src/engine/bytecode/iterator.rs
- nova_vm/src/engine/bytecode/vm.rs
- nova_vm/src/engine/bytecode/vm/binding_methods.rs
This doesn't make iterators fully GC-safe yet; the VmIterator system is a bit of a sharp edge here. I will find a solution for it eventually, but it's not quite here yet.
> chore(engine): IteratorRecord lifetime

- nova_vm/src/ecmascript/builtins/indexed_collections/typed_array_objects/typed_array_intrinsic_object.rs
It looks like toSpliced and splice don’t exist on TypedArray!
There was no splice, but toSpliced did exist, so I removed it!
ref: https://github.com/tc39/proposal-change-array-by-copy/issues/88
> chore(ecmascript): remove TypedArray toSpliced

- nova_vm/src/engine/bytecode/bytecode_compiler.rs
- nova_vm/src/engine/bytecode/executable.rs
- nova_vm/src/engine/bytecode/instructions.rs
- nova_vm/src/engine/bytecode/vm.rs
- nova_vm/src/engine/bytecode/vm/binding_methods.rs
- nova_vm/src/heap/heap_gc.rs
Couldn't run Kraken benchmark's `ai-astar.js` without larger jump slots.
> feat(vm): Use 32-bit integers for jump slots

- .github/workflows/ci.yml
- .gitignore
- Cargo.toml
- tests/test262_runner.rs
Adds a `dev-fast` build profile and uses it to run Test262 in CI.
Using this profile trades slightly longer compile times for much faster run times. It takes ~10s longer to build dev builds while taking half the time of release builds, but runs tests 300x faster than dev while only being marginally slower than release builds.
Below are build/test times collected (quite non-scientifically) from my local machine (m1 mac pro, 16gb).
* Each build is "clean" (`cargo clean && cargo build --profile <profile>`).
* Test262 times are in "real" time (`/usr/bin/time -h cargo run --bin test262 --profile <profile>`)
|         | dev      | dev-fast | release |
|---------|----------|----------|---------|
| build   | 27.07s   | 39.83s   | 1m 06s  |
| test262 | 1m32.19s | 33.70s   | 33.58s  |
- Move spell …
> build: run test262 with new dev-fast profile

- nova_vm/src/ecmascript/builtins/indexed_collections/typed_array_objects/abstract_operations.rs
- nova_vm/src/ecmascript/builtins/indexed_collections/typed_array_objects/typed_array_intrinsic_object.rs
Removes a *lot* of duplicate code within the code for typed arrays by introducing a `with_typed_array_viewable` which automatically matches the typed array variant to the corresponding `Viewable` type.
> chore: `with_typed_array_viewable` macro to reduce duplicate code

- nova_vm/Cargo.toml
- nova_vm/src/builtin_strings
- nova_vm/src/ecmascript/builtins/structured_data/atomics_object.rs
Literally just a nop in our case. Added a todo for compiling it to a byte code instruction and a processor specific `pause` (https://doc.rust-lang.org/std/hint/fn.spin_loop.html probably as it compiles to `_mm_pause`/`pause`).
> feat(ecmascript): Implement `Atomics.pause` proposal

- nova_vm/src/ecmascript/builtins/indexed_collections/typed_array_objects/typed_array_intrinsic_object.rs
~~depends on PR: https://github.com/trynova/nova/pull/663~~
~~The implementations of each method have been moved into the ones defined in Viewable.~~
~~For example, operations like retrieving the length have become simpler by using Viewable.~~
I refactored the code, but now I’m thinking that since with_typed_array_viewable allows you to use methods on T: Viewable, it might not be necessary to extract them into separate functions.
Let me know if you have any thoughts on this.
> chore(ecmascript): refactor reverse and copy_within

- nova_vm/src/ecmascript/types/language/number.rs
- nova_vm/src/engine/bytecode/vm.rs
- tests/parse_expectations.js
A stderr debug print had been left in by me, and that was being picked up by test262.fyi but not by our tests, hence the discrepancy.
> chore(tests): Fix test262.fyi failures

- nova_vm/src/engine/bytecode/bytecode_compiler.rs
- nova_vm/src/engine/bytecode/bytecode_compiler/compile_context.rs
- nova_vm/src/engine/bytecode/bytecode_compiler/executable_context.rs
- tests/expectations.json
- tests/metrics.json
Just a bit of this and that minor bytecode perf work.
> perf(vm): Skip unreachable code, remove redundant Jumps, avoid Push/PopReference when binding literals to variables

- nova_vm/src/ecmascript/scripts_and_modules/script.rs
A `"use strict"` directive at the script top level didn't actually make the script run as strict.
> fix(ecmascript): Propagate 'use strict' directives to script execution contexts

- small_string/lib.rs
`SmallString::is_ascii` was checking that each byte was both a padding byte AND and ascii byte, leading it to always return `false.`
> fix(small_string): SmallString::is_ascii

- nova_vm/src/ecmascript/builtins/arguments.rs
- nova_vm/src/ecmascript/builtins/array.rs
- nova_vm/src/ecmascript/builtins/bound_function.rs
- nova_vm/src/ecmascript/builtins/builtin_constructor.rs
- nova_vm/src/ecmascript/builtins/builtin_function.rs
- nova_vm/src/ecmascript/builtins/control_abstraction_objects/promise_objects/promise_abstract_operations/promise_resolving_functions.rs
- nova_vm/src/ecmascript/builtins/ecmascript_function.rs
- nova_vm/src/ecmascript/builtins/error.rs
- nova_vm/src/ecmascript/builtins/module.rs
- nova_vm/src/ecmascript/builtins/ordinary.rs
- nova_vm/src/ecmascript/builtins/ordinary/caches.rs
- nova_vm/src/ecmascript/builtins/ordinary/shape.rs
- nova_vm/src/ecmascript/builtins/primitive_objects.rs
- nova_vm/src/ecmascript/builtins/proxy.rs
- nova_vm/src/ecmascript/builtins/regexp.rs
- nova_vm/src/ecmascript/builtins/typed_array.rs
- nova_vm/src/ecmascript/types/language.rs
- nova_vm/src/ecmascript/types/language/function.rs
- nova_vm/src/ecmascript/types/language/function/into_function.rs
- nova_vm/src/ecmascript/types/language/object.rs
- nova_vm/src/ecmascript/types/language/object/internal_methods.rs
- nova_vm/src/ecmascript/types/language/object/property_storage.rs
- nova_vm/src/ecmascript/types/language/primitive.rs
- nova_vm/src/ecmascript/types/language/string.rs
- nova_vm/src/ecmascript/types/language/value.rs
- nova_vm/src/engine/bytecode/vm.rs
Change the API of [[Set]] cached to take parameters in a bag and use that to pass the PropertyCache all the way through the callstack. Then, use that when installing a new property on an object to immediately create a property lookup cache.
> refactor(ecmascript): cached_set install lookup on push
